= README

Goal: Converting pyret-docs from Scribble to Pollen.

Also: Controlling https://getbootstrap.com[Bootstrap Web Framework] elements from Pollen.

== Where (the repos)

The Pollenized Pyret docs, along with its tailormade Pollen macro
files, are currently in the `new-docs` subdirectory of the repo
https://github.com/ds26gte/pyret (fork), in the branch `new-docs`.

Eventually they will move into the standard repo
https://github.com/jpolitz/pyret.

The source docs may be browsed at

  https://github.com/ds26gte/pyret/tree/new-docs/new-docs

It uses general (i.e., non Pyret-doc-specific) Pollen extensions
from the repo https://github.com/ds26gte/pollenboots. (This repo
needs to move to a more canonical location.)

The most current HTML-rendered version of the Pollenized Pyret doc
is at https://ds26gte.github.io/pyret-docs-pb/index.html. It
should be viewable on both large screen and phones.

== How

. Ensure you have Racket installed on your computer
. Ensure you have the Pollen package installed: `raco pkg install --auto pollen`
. Clone this repo: i.e., `git clone https://github.com/ds26gte/pyret`
. Ensure you're on the `new-docs` branch of the repo
. `cd` to the directory `new-docs`
. Type `make` to create the HTML pages locally
. Browse the created `index.html`

While you can directly bring up `index.html` on your web browser,
in order to get the Pyret embeds working, you will need to serve
the pages via an http server, e.g., the NPM `http-server`:

  http-server -p 3000 --cors

Browse to http://localhost:3000.

WARNING: The Pyret embeds _will not work_ on
https://ds26gte.github.io/pyret-docs-pb/index.html -- use that URL
only to check static content. The embeds do work
on a local build, after calling `http-server -p 3000 --cors` in
the `new-docs` directory, and browsing to http://localhost:3000.

== What

https://docs.racket-lang.org/pollen[Pollen] allows the use of
Racket to create complicated Web pages in particular, and also
other outputs. Since Bootstrap seems to be HTML only, we'll
restrict ourselves to HTML. However, our source is in `poly`
format, so we could go to other output formats if needed.

Pollen macros and source files for the Pyret docs are
included alongside the source for the docs, i.e., in the new-docs
subdirectory.

The file index.ptree is a _page tree_ of the various document
files (using the .html extension!), in the preferred order. The
source files for this .html's are the *.poly.pm files, placed in
the appropriate (sub)directories.

The file template.html.p provides the boilerplate for the
generated .html.

The Pollen rendering is guided by the file pollen.rkt, which
defines directives that can be used in the .poly.pm, but can also
provide a `root` procedure that allows a full-source
transformation of the per-file Pollen intermediate format. This
allows non-local transformations like adding a table of contents,
glossary, and cross references -- i.e., things that cannot be done
simply by defining locally transforming directive procedures
(although a local directive may still need to auto-include the
anchor points).

Luckily, these global Pollen additions are sufficiently general --
i.e., not specific to Pyret doc -- that we can develop them
in a dedicated repo,
https://github.com/ds26gte/pollenboots[Pollenboots]. This
repo contains a pollen.rkt with a definition for `root` that does the
ToC and xrefs, and in our Pyret docs directory, we will have our
pollen.rkt slurp in the pollenboots' pollen.rkt. While our
pollen.rkt will define local directives (using subfiles as
needed), it will use the pollenboots' `root` directly, as that
already takes care of all the global transformations we need. (We
don't need a separate wrapper `root`.)

In addition, the pollenboots' pollen.rkt allows a more author-convenient
input style, viz., with blank lines signifying paragraph separation,
automatic conversion to smart quotes and dashes, automatic
creation of external title.

Please look at the pollenboots doc for specifics on its
pollen.rkt. Now we will briefly describe the kinds of directives that the
pyret-docs' pollen.rkt provides:

- The first are a series of code-display directives, such as
◊pyret, ◊pyret-id, ◊examples, etc. These are exactly modeled on
the similarly named @-functions in the Scribble version.

- Then we have some abbreviations for type annotations (`A` for
`Any`, `B` for `Boolean`, etc). Again these match the convention
set by Scribble.

- Finally we have some larger paragraph-formatting directives such
as ◊form, ◊type-spec, etc.

Although these are seemingly local directives, they do use some of
the utilities from the pollenboots' pollen.rkt in order to
automatically insert anchor points for the cross-references,
glossary entries, and ToC entries.
